name: Noticeboard backend test

on:
   push:
     branches: [ development ]

   pull_request:
     branches: [ development ]

jobs:
   test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 
      uses: actions/setup-python@v2
      with:
         directory: backend/notice_project/
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run unittest
      run: |
        python manage.py test
